@startuml Smart City Cross-Domain

!include smart-city-topology.puml

' entity Address <<context>> {
'     ' addressCountry: string
'     addressLocality: string
'     addressRegion: string
'     ' postOfficeBoxNumber: string
'     ' postalCode: string
'     ' streetAddress: string
' }

entity NGSILDBaseModel <<abstract>> {
    ' dataProvider: string /' Specifies the URL to information about the provider of this information '/
    ' dateModified: dateTime
    ' dateCreated: dateTime
    ' source: string /' A sequence of characters giving the source of the entity data '/
    ' alternateName: string /' An alias for the entity. '/
    name: string /' The name of the entity. '/
    ' description: string /' A description of the entity. '/
    ' owner: string
    ' seeAlso: string /' List of comma separated URLs to one or more related entities. '/
}

NGSILDBaseModel *-- GeoLocation : location

' NGSILDBaseModel *-- Address : address

@enduml