@startuml Energy Grid Transformer

!include energy-grid-equipment.puml
!include energy-grid-region.puml

' The type of substations
enum SubstationType {
    MV_MV_substation
    MV_LV_substation
    LV_LV_substation
}

' An electrical device consisting of two or more coupled windings, with or without a magnetic core, for introducing mutual coupling between electric circuits.
' Transformers can be used to control voltage and phase shift (active power flow).
' A power transformer may be composed of separate transformer tanks that need not be identical.
' A power transformer can be modelled with or without tanks and is intended for use in both balanced and unbalanced representations.
' A power transformer typically has two terminals.
entity PowerTransformer extends ConductingEquipment {
    Name: string /' Power transformer name. For example, SAMWA0001 '/
    PowerTransformerEnd: double /' The power transformer of this power transformer end. '/
    beforeShCircuitHighestOperatingCurrent: double /' The highest operating current (Ib in the IEC 60909-0) before short circuit (depends on network configuration and relevant reliability philosophy). It is used for calculation of the impedance correction factor KT defined in IEC 60909-0. Default: 0.0 '/
    beforeShCircuitHighestOperatingVoltage: double /' The highest operating voltage (Ub in the IEC 60909-0) before short circuit. It is used for calculation of the impedance correction factor KT defined in IEC 60909-0. This is worst case voltage on the low side winding (Section 3.7.1 in the standard). Used to define operating conditions. Default: 0.0 '/
    beforeShortCircuitAnglePf: double /' The angle of power factor before short circuit (phib in the IEC 60909-0). It is used for calculation of the impedance correction factor KT defined in IEC 60909-0. This is the worst case power factor. Used to define operating conditions. Default: 0.0 '/
    highSideMinOperatingU: double /' The minimum operating voltage (uQmin in the IEC 60909-0) at the high voltage side (Q side) of the unit transformer of the power station unit. A value well established from long-term operating experience of the system. It is used for calculation of the impedance correction factor KG defined in IEC 60909-0 Default: 0.0 '/
    isPartOfGeneratorUnit: double /' Indicates whether the machine is part of a power station unit. Used for short circuit data exchange according to IEC 60909 Default: False '/
    operationalValuesConsidered: double /' It is used to define if the data (other attributes related to short circuit data exchange) defines long term operational conditions or not. Used for short circuit data exchange according to IEC 60909. Default: False '/
}

' A PowerTransformerEnd is associated with each Terminal of a PowerTransformer.
' The impedance values r, r0, x, and x0 of a PowerTransformerEnd represents a star equivalent as follows.
' 1) for a two Terminal PowerTransformer the high voltage (TransformerEnd.endNumber=1)
' PowerTransformerEnd has non zero values on r, r0, x, and x0 while the low voltage (TransformerEnd.endNumber=2)
' PowerTransformerEnd has zero values for r, r0, x, and x0.
' Parameters are always provided, even if the PowerTransformerEnds have the same values.
entity PowerTransformerEnd {
    ' b: float /' Magnetizing branch susceptance (B mag).  The value can be positive or negative. '/
    ' g: float /' Magnetizing branch conductance. '/
    ' r: float /' Resistance (star-model) of the transformer end. The attribute shall be equal to or greater than zero for non-equivalent transformers. '/
    ratedS: float /' Normal apparent power rating. The attribute shall be a positive value. For a two-winding transformer the values for the high and low voltage sides shall be identical. '/
    ' ratedU: float /' Rated voltage: phase-phase for three-phase windings, and either phase-phase or phase-neutral for single-phase windings. A high voltage side, as given by TransformerEnd.endNumber, shall have a ratedU that is greater than or equal to ratedU for the lower voltage sides. The attribute shall be a positive value. '/
    ' x: float /' Positive sequence series reactance (star-model) of the transformer end. '/
    ' PowerTransformer --> PowerTransformer /' The power transformer of this power transformer end. '/
    ' connectionKind --> WindingConnection /' Kind of connection. '/
}

' A collection of equipment for purposes other than generation or utilization, through which electric energy in bulk is passed for the purposes of switching or modifying its characteristics.
entity Substation extends EquipmentContainer {
    substationName: string /' The name of the substation. '/
    substationType: SubstationType /' The type of substations. '/
    ' dcConverterUnit --> DCConverterUnit /' The DC converter unit belonging of the substation. '/
    ' locatedAt --> SubGeographicalRegion /' The SubGeographicalRegion containing the substation. '/
}

PowerTransformerEnd --> PowerTransformer : PowerTransformer /' The power transformer of this power transformer end. '/

PowerTransformer --> PowerTransformerEnd : PowerTransformerEnds /' The ends of this power transformer. '/

PowerTransformer --> Substation : MemberOf_Substation /' The associations for PowerTransformer containment are: Substation -> PowerTransformer -> TransformerWinding '/

Substation --> SubGeographicalRegion : locatedAt /' The SubGeographicalRegion containing the substation. '/

@enduml
