@startuml Energy Grid

!include energy-grid-substation.puml
!include energy-grid-usage-point.puml
!include energy-grid-electric-vehicle.puml
!include energy-grid-customer-load.puml
!include energy-grid-equivalent-load.puml

@enduml