@startuml Energy Grid Region

!include energy-grid-common.puml
!include energy-grid-location.puml

' A subset of a geographical region of a power system network model.
entity SubGeographicalRegion <<context>> extends IdentifiedObject, Location {
}

' A geographical region of a power system network model.
' entity GeographicalRegion extends IdentifiedObject, Location {
' }

' SubGeographicalRegion --> GeographicalRegion : withIn /' The geographical region which this sub-geographical region is within. '/

@enduml